### ISSUE TITLE
Switching Out Fire-Picker

### ISSUE THREAD

**Issue by PressJump** [focus-browser/browser#126]
Firefox Translations an extension developed by Mozilla available is not included with base Firefox but a great addition for users who visit websites that are not written in their system language. https://addons.mozilla.org/en-US/firefox/addon/firefox-translations/ 

This would be a great addition for improving user experience.

**Comment by PressJump** [comment]
What are your thoughts about this @trickypr

**Comment by trickypr** [comment]
Should be fine

**Comment by PressJump** [comment]
Fire-picker at this point of time is dead and needs for a rewriting in terms of injection and optimization, more information can be found at the issue https://github.com/pulse-browser/fire-picker/issues/3 . In the state of feature freeze it is a good idea to replace it with Firefox Translations until Fire-Picker gets to a point that is usable.

**Comment by PressJump** [comment]
On startup firefox-translations spawns a window asking "Allow Firefox Translations to send technical and interaction data to Mozilla?".
![image](https://user-images.githubusercontent.com/40802367/194676062-ca2c9b2f-7609-49d1-a077-34598574c3c6.png)
![image](https://user-images.githubusercontent.com/40802367/194676077-bbfafe56-e55c-4ece-a0df-552e1fff610b.png)

**Comment by PressJump** [comment]
After thought, due to problems which would be caused from maintaining a modified version of translations it may be a good idea to switch out Fire-Picker with https://github.com/pulse-browser/firefox-qr-generator an in house productivity extension.
