### ISSUE TITLE
Sidebar Scrollbar

### ISSUE THREAD

**Issue by PressJump** [focus-browser/browser#127]
Sidebar scrollbar for scrolling down on over limit sidebar items is too large and located awkwardly on the whole sidebar rather than the dynamic items only.

Issue made for tracking.

**Comment by niutech** [comment]
On Windows, I always see the scrollbar in sidebar, even though there are no additional icons over the default ones:

![Scrollbar](https://user-images.githubusercontent.com/384997/197362896-d12d7353-38c9-4537-a325-22ace42ac1ba.png)

**Comment by PressJump** [comment]
> On Windows, I always see the scrollbar in sidebar, even though there are no additional icons over the default ones:
> 
> ![Scrollbar](https://user-images.githubusercontent.com/384997/197362896-d12d7353-38c9-4537-a325-22ace42ac1ba.png)

This should be hidden in the next build of the browser as it was fixed on https://github.com/pulse-browser/browser/pull/129 . Normally the scrollbar would show up even without any other items so I have just hidden it completely as it does not look that great.
