### ISSUE TITLE
Sidebar Expansion contains race condition

### ISSUE THREAD

**Issue by trickypr** [focus-browser/browser#130]
If a significant number of items resolve at the same time when adding items to the sidebar, they will overwrite themselves in storage. State should be handled centrally to avoid this. Race condition occurs in [this function](https://github.com/pulse-browser/sidebar-tabs/blob/04668bcaed6ebdb5094c9be8ceb3e5ee489e7234/js/main.js#L63)

**Comment by PressJump** [comment]
3am thoughts, I can see this problem including the removing function not removing overwritten content.
