### ISSUE TITLE
Vertical tabs

### ISSUE THREAD

**Issue by trickypr** [focus-browser/browser#137]
This needs more thought before implementing, but here are some general ideas, but the genreal gist is that we should have something like Edge's vertical tabs. Here are my current thoughts, but design and UX work is needed:

1. It should be the option of one or the other, not both at the same time
2. Vertical tabs might be an interesting way of handling tab grouping, sort of like a merge of [Tree style tabs](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab) and [Chrome's tab grouping](https://blog.google/products/chrome/manage-tabs-with-google-chrome/)
3. It **must** feel native, unlike Tab Center Reborn + UserChrome

Technical thoughts:
- Would we be able to just move the location of the tab container? Would that be too slow because of how complex the dom is? Would that break existing functionality?

References / links:
- Tab Center Reborn is broken on pulse: #134 
- [uc.css.js's](https://github.com/aminomancer/uc.css.js) includes an implementation, which might have some interesting ideas for structure, but we do not want to rip them off.

## TODO
- [x] Basic implementation (#167)
- [ ] Clean up the pulse theme
- [x] Add the option to compress the tabs down to just the favicon when not hovered
- [ ] Profit?

**Comment by trickypr** [comment]
I now have a vertical tab example. I am going to end up moving tab grouping elsewhere, because it will take longer to land. The design isn't finalized (and won't be for a while), but I want to get user feedback as soon as I can.

![image](https://user-images.githubusercontent.com/23250792/204497612-7fe9d5bc-7c9d-414e-a03a-474a8421a1ab.png)

The current implementation just copy-pastes the browsers tab to the side. There is a bit of glue to make sure that everything works well, and some css rules.

**Comment by ghost** [comment]
umm thats not very very pretty... looks like _IE*_
no offense

**Comment by trickypr** [comment]
Do you mean edge? IE didn't have a vertical tab bar

But yea, this is intended to be a first draft to experiment with the tech before I put any effort into doing proper mockups etc.

**Comment by ghost** [comment]
no, i forgot the name of the browser, but it is a very very old browser

(i made a suggestion that i didn't see you had already put in the TODO list sorry)


also what do you mean with this?
<br>
![image](https://user-images.githubusercontent.com/111013695/205515258-b2be6b7f-5543-444b-9c37-6f30a115ae15.png)

**Comment by SeongGino** [comment]
I only just found out about this project a few days ago, and so far I enjoy the idea of the vertical tabs. However, coming from the traditional tab bar, I have a few observations:

 - Normal tab bar allows for quickly opening new tabs by middle clicking empty padding, but doesn't seem to be available in the vertical tabs panel.
 - Collapsible tab bar is my preference, but the drag bar is still active in collapse mode - it just doesn't do anything/immediately collapses when set in that mode.
 - When collapsed, the new tab button at the bottom--specifically the plus icon--is off-centered. Might be better to reposition this, either when collapsed or remove the padding?
 - On the note of the drag bar, it seems redundant to allow this when the tab space seems limited to a fixed size? I.e. the close button only appears after a certain amount of units visible, and the tab text can't expand beyond this.
 - Would it be possible to be able to scale up the individual tabs' size, or even just the favicon? Just to make the buttons a bit bigger, or an option for a tab-icon-only view when collapsed.
 - Having the option to disable showing the close tab button in about:preferences would be nice; likewise for the new tab button, if the ability to middle-click-to-new-tab is implemented.

Maybe this should be in its own issue? I'm not sure. But would be interested in hearing responses to this.

**Comment by Kvn0l** [comment]
I would like to add a request here about the vertical tabs, much better than opening a new issue since is something small :)

I didn't saw any option to switch tabs with mouse wheel scroll, like this for example: https://addons.mozilla.org/firefox/addon/tree-style-tab-mouse-wheel , so I would be happy to see this function implemented.
Thanks!

**Comment by trickypr** [comment]
@SeongGino Most of your requests should have been covered now
