### ISSUE TITLE
Websites should remain active even when a tab is closed

### ISSUE THREAD

**Issue by trickypr** [focus-browser/browser#146]
Original report:

<div type='discussions-op-text'>

<sup>Originally posted by **juush** November 14, 2022</sup>
Would be nice if you could "minimize" the side bar tabs.
I'd like to have pandora playing from the browser but not have to have the tab open the entire time!</div>

**Tl;Dr:** Websites in the sidebar should remain active even when they are closed / hidden. This might need some significant engineering to get it to work correctly, so I will probably be the one to take it on.

**Comment by PressJump** [comment]
Will be adding an option to unload pages rather than minimize them for users who don't want to utilize the feature. Otherwise enabled by default.
