### ISSUE TITLE
update Betterfox.js

### ISSUE THREAD

**Issue by yokoffing** [focus-browser/browser#152]
The [version you're using](https://github.com/pulse-browser/browser/blob/alpha/src/browser/app/profile/better-fox.js) is over a year old:

https://github.com/pulse-browser/browser/blob/d9f66264442f94fc8e71b4e89285b0f8182ceb88/src/browser/app/profile/better-fox.js#L13

The file for FF v.107 stable will be out in a few days and will be available [here](https://github.com/yokoffing/Betterfox/blob/master/user.js).

Edit: Updates are pushed monthly, usually.

**Comment by splatboydev** [comment]
This will most likely be added by tomorrow.
