### ISSUE TITLE
hide sidebar in simple windows (no omnibox)

### ISSUE THREAD

**Issue by Sam-Oak** [focus-browser/browser#158]
i don't think it's useful to in this context.
![image](https://user-images.githubusercontent.com/62823895/202820404-b450184b-71f6-46d6-88d3-9b5cacbbac8a.png)

**Comment by PressJump** [comment]
This is fair especially on login windows forexample. Tagging this as a bug. I will get to this after PR #159 and PR #165 as they are quite large.
