### ISSUE TITLE
Input from Linux Game Cast: LWDW 352

### ISSUE THREAD

**Issue by trickypr** [focus-browser/browser#160]
See [LWDW 352](https://linuxgamecast.com/2022/11/lwdw-351-fedora-37-and-davinci-resolve-18-1/#).

- [ ] The sidebar should be easier to disable (should this be an option in the startup options?)

P.S. If you are the original author, we are always open to feedback

**Comment by PressJump** [comment]
Point taken. Maybe option on startup but could also do a introductory page to sidebar that automatically opens in the sidebar that has a button to disable if not wanted. This would make it so that the setup screen does not go for so long.

**Comment by PressJump** [comment]
Although setup sounds more stable for sure.

**Comment by PressJump** [comment]
The current implementation on PR #165 fixes this problem and makes it easier for a person to enable or disable sidebar related preferences off the start. 
![image](https://user-images.githubusercontent.com/40802367/203498187-8139ea78-c6f0-4c18-a603-7ee99dab6f1a.png)
