### ISSUE TITLE
Context menu shows literally every option no matter what was right clicked

### ISSUE THREAD

**Issue by Void-025** [focus-browser/browser#169]
Example:
![image](https://user-images.githubusercontent.com/44403167/205447086-1af26091-3086-4cf1-a208-1cf71267975b.png)

This was from right clicking empty space on the start page. As far as I can tell, there's no situation in which it'll ever show anything different. Options that don't make sense in the current context don't do anything when clicked, while ones that do ("copy" when having text selected for example) function as expected.

**Comment by trickypr** [comment]
Temporary fix, set `extensions.pocket.enabled` to `false`. Must have been broken with #155. A proper fix will roll out once the attached PR merges.
