### ISSUE TITLE
Update is available popup on every fresh start

### ISSUE THREAD

**Issue by soulspark666** [focus-browser/browser#173]
![image](https://user-images.githubusercontent.com/37495396/207912519-a49694f4-c767-4b01-bce2-146bd5cf67d5.png)
![image](https://user-images.githubusercontent.com/37495396/207912610-b5966288-29cf-421c-9f96-0d2f814fbdd4.png)

As we can see I have the latest release but I get a constant popup on every fresh start that there is an update pending and pulse was not able to apply it automatically.

![image](https://user-images.githubusercontent.com/37495396/207913069-cca333c8-59a8-437d-85e8-fb9bafc735b2.png)

**Comment by PressJump** [comment]
Hey @soulspark666 ,
Sorry for the late reply as we are busy around this time due to events and etc.. This used to be a problem only on older versions of pulse and I am unsure on why this is happening to you. Due to this I will tag this issue as a bug for a potential fix on a future release of pulse after an investigation on this version.

**Comment by jonatancortes** [comment]
Thanks @PressJump  
I have exactly the same problem as described here, also with version 1.0.0-a.48.

When I click on 'Update available - Download now' it goes to [Firefox Nightly page](https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly).

**Comment by soulspark666** [comment]
@PressJump don't want to spoil the festivities but this thing is getting more and more annoying I get these popups while browsing too now, is there a way to temporarily stop the update popup??

**Comment by PressJump** [comment]
> Thanks @PressJump I have exactly the same problem as described here, also with version 1.0.0-a.48.
> 
> When I click on 'Update available - Download now' it goes to [Firefox Nightly page](https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly).

Thank you for the information, I was away for a little due to reasons but will pickup this issue as I have personally been getting them on my Windows machine as well.

**Comment by PressJump** [comment]
> @PressJump don't want to spoil the festivities but this thing is getting more and more annoying I get these popups while browsing too now, is there a way to temporarily stop the update popup??

Sorry for the late answer as I was away for a little. There is a thread available on mozilla support talking about this https://support.mozilla.org/en-US/questions/1327455 and I believe you will need to disable updates all together but I will continue to look into this. Until then please try to update your browser through our executable on our downloads.

**Comment by soulspark666** [comment]
Ik this got closed with the recent merge but was this not released since there are no new release after the  a.48

**Comment by trickypr** [comment]
Sorry about that, the packager is broken. I will go fix it and trigger another CI run

**Comment by soulspark666** [comment]
@trickypr seems like windows pipeline is still broken.

**Comment by trickypr** [comment]
Looks like I left a terminal open on the runner and it broke everything :(
