### ISSUE TITLE
How to Disable uBlock Origin

### ISSUE THREAD

**Issue by eeriemyxi** [focus-browser/browser#179]
I am wanting to use Pulse Browser rather than plain Firefox, but I'm not interested to use uBlock Origin again. I have recently started using [AdNauseam](https://github.com/dhowe/AdNauseam/), a fork of uBlock Origin; and I'm just loving it so much. Is there a way for me to replace uBlock Origin with that, or to disable it entirely?

**Comment by splatboydev** [comment]
It's added into the browser itself, but you could modify the ``gluon.json`` addons to remove it.

**Comment by eeriemyxi** [comment]
> It's added into the browser itself, but you could modify the `gluon.json` addons to remove it.

I renamed `uBlock0@raymondhill.net.xpi` in `browser/features`, and that worked as well.
