### ISSUE TITLE
More Browser Imports

### ISSUE THREAD

**Issue by PressJump** [focus-browser/browser#186]
Currently, there is a limited amount of browser imports available. It would make it easier for new users who are trying out pulse for transferring their data over from other browsers that are not already available if there was more options. Usually most browsers that are not already available on the list use same types of storage to hold user data as they are forks of chrome/firefox (like us).

**Comment by trickypr** [comment]
Upstream implementation will be available in 109 on the 17th. I say we wait it out.

Bugzilla tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1800934

**Comment by PressJump** [comment]
> Upstream implementation will be available in 109 on the 17th. I say we wait it out.
> 
> Bugzilla tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1800934

Yea that is a fair call.
