### ISSUE TITLE
Browser looks different when on dark mode

### ISSUE THREAD

**Issue by stantios** [focus-browser/browser#203]
Browser Version: 1.0.0-a.53
Operating System: MacOS
MacOS Version: 10.13.6

Description: The dark mode on this browser looks different to the dark mode on regular firefox, this also happens with the theme called 'Pulse Dark'.
Screenshots - Firefox: 
![image](https://user-images.githubusercontent.com/98621617/214670466-3b5b6e31-733b-42d0-a724-6fafbd19f328.png)

Pulse Browser: 
![image](https://user-images.githubusercontent.com/98621617/214670605-8a1f43eb-6fdb-40d2-95b9-351025cfda72.png)

**Comment by trickypr** [comment]
Looks like transparency broke again, I will look into this

**Comment by pvinis** [comment]
theres also a few places like:
- app opening dialog (the dialog where you chose which app to open a url with, for example if a `mailto:` or `magnet:` link is clicked)
- Settings > General > Browser (all the `Learn more` links are not visible in dark mode)
