### ISSUE TITLE
Cannot sign in with Firefox

### ISSUE THREAD

**Issue by JMcrafter26** [focus-browser/browser#207]
Hello there, 

I tested this browser for a week now and everything was fine until now.
I logged in with Firefox a few days ago to synch my browser history, tabs, etc. and now that option is gone.

Furthermore, I cannot find the option to log in or synch my history.

Please help

PS: The sidebar synched tabs sign in button leads to the browser settings, where I also cannot find the option to login
![image](https://user-images.githubusercontent.com/77780772/218270523-242e8210-a8ef-4f35-9d32-24bcae26e333.png)

![image](https://user-images.githubusercontent.com/77780772/218270535-18d4b893-47eb-48a2-8da4-23d24189a4fe.png)

**Comment by trickypr** [comment]
Sorry about that, #206 included a number of tweaks, which disabled a few things. #208 contains a fix. You can manually apply said fix by:
1. Opening `about:config` and clicking "Accept the risk and continue" 
2. Search for `identity.fxaccounts.enabled`
3. Set `identity.fxaccounts.enabled` to `true`
4. Restart the browser
5. Sync should now appear as an option on the left sidebar in settings. There should also be a "Sign In" button in the hamburger menu
