### ISSUE TITLE
[BUG] Forget remove login from alll sites

### ISSUE THREAD

**Issue by soulspark666** [focus-browser/browser#215]
Using forget for a duration seems to log out from all sites.
![image](https://user-images.githubusercontent.com/37495396/220705085-c3cf738d-e4e2-4a98-8a78-be0ac54fcced.png)

The usual behavior was, it will log out from sites that were open in that duration, eg: if I went and signed in on pixiv and gmail in a 5-minute duration and I used to forget for 5 minute then it will log me out from pixiv but gmail used to stay. Right now I am also logged out from Github and all other sites that I may have logged in previously days before.

It is my guess that this started happening from: 1.0.0-a.59 version

**Comment by trickypr** [comment]
Odd. I cannot reproduce this. Running forget for me did not log me out of Github or Google. If you are able to provide clearer reproduction details (on a new profile, ideally), I will look into it.

**Comment by soulspark666** [comment]
@trickypr I uninstalled the app completely using BC uninstaller, also removed the profile folder from the app data, still it is having same issues:

## Logged in:
![image](https://user-images.githubusercontent.com/37495396/221606840-025d3b24-9e1a-45a2-b2bd-36b5f8b202ea.png)

## Forget in around 7 min to be beyond the 5 min selected:
![image](https://user-images.githubusercontent.com/37495396/221606915-a257d28d-29ce-4a3f-a087-2e3b765f5a3b.png)

## Logged out of github:
![image](https://user-images.githubusercontent.com/37495396/221607086-b5e58783-32f2-4246-97ab-88147f27dab4.png)

## Version information for the current release:
![image](https://user-images.githubusercontent.com/37495396/221607388-0d72ae2d-4542-4101-bd08-39e064128109.png)

**Comment by trickypr** [comment]
Upstream issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1816279

Will be fixed with updating to 110.0.1, which will hopefully happen in the next few days
