### ISSUE TITLE
Twitch.tv not working

### ISSUE THREAD

**Issue by noahnao** [focus-browser/browser#223]
First of all love this project,
Second of all Twitch.tv is not currently working, and it states that the browser is unsupported.
Picture of problem
![Skærmbillede 2023-03-12 011719](https://user-images.githubusercontent.com/81416193/224517372-df19f662-67f3-44e9-8857-fd0fdd07f689.png)

**Comment by trickypr** [comment]
Steps to reproduce:
1. Create a new profile in `about:profiles` (this will not occur if you have already opened twitch on your current profile)
2. Open `https://www.twitch.tv/`
3. Attempt to log in with an existing account
4. Get the above error

At least for me I was able to fix this by refreshing twitch and trying to log in again, which worked. Not sure what is going on there, but your mileage may vary with that fix.

**Comment by noahnao** [comment]
Yeah i tried that, then i tried disableing ublock, then Privacy badger, then LocalCDN, Then Enhanced tracking protection, then turned off network.http.referer.XOriginPolicy. None of it worked, i really want to love this browser but there is a lot that needs to be fixed.

**Comment by noahnao** [comment]
This was an issue with the config settings that i enabled.
