### ISSUE TITLE
Pulse Update Download Button Wrong Destination

### ISSUE THREAD

**Issue by garygriffiths1977** [focus-browser/browser#225]
When I receive the Pulse Update notification and click the "Download" button, I am taken to the Firefox Nightly page.

![Screen Shot 2023-03-14 at 9 07 28 am](https://user-images.githubusercontent.com/10218258/224866533-c02d1e19-934b-4115-8565-43f09ef63f57.png)

By the way, absolutely loving Pulse over Firefox. Keep up the great work guys.

**Comment by ethpsantos** [comment]
Happened to me today... it go to the Firefox Nightly Build instead.
