### ISSUE TITLE
Add/edit bookmark menu not showing when pressing Coltrol D

### ISSUE THREAD

**Issue by thepick** [focus-browser/browser#244]
What I want to happen: I want to press Control-D and have the menu to add/edit bookmark menu pop up when browsing the web

What actually happens: The menu to edit bookmarks fails to show. There is a fast flash to the right of the URL bar. It will show if I'm in the Proton settings page, though.

As a side (possibly related?) note, the bookmark star is gone from the right-hand side of the url bar, and if I right-click a web page and add a bookmark that way the add/edit bookmark menu fails to show. The newly created bookmark just goes somewhere without the ability to organize it properly.

**Comment by trickypr** [comment]
I have a suspicion this is related to #242. Will need to check once merged.

**Comment by trickypr** [comment]
Confirmed this is fixed in `1.0.0-a.64`
