### ISSUE TITLE
Browser Sidebar

### ISSUE THREAD

**Issue by PressJump** [focus-browser/browser#25]
Add a visible sidebar to pulse browser that will facilitate the space to add more features that are readily accessible on the user's screen. The proposed sidebar includes room for default actions like bookmarks, history, tabs and extensions that want to utilize the sidebar.

**Comment by trickypr** [comment]
Note that the first iteration of this is done for the moment. In the future we may try to add the ability to customize the items in the sidebar, but that is a future change
