### ISSUE TITLE
32-bit Build

### ISSUE THREAD

**Issue by golf1487** [focus-browser/browser#253]
When is 32-bit build coming on Windows at least from the start?

As you can see, 32-bit is lighter on resources and works fine:

https://www.mozilla.org/en-US/firefox/113.0.1/system-requirements/

**Comment by trickypr** [comment]
Probably not officially. Windows is barely supported as it is and the performance improvement that you will get from 32bit wont be significant.

If you want to have a crack at setting up a 32bit CI, go ahead.
