### ISSUE TITLE
Dialog box needs styling on dark themes

### ISSUE THREAD

**Issue by Zenko** [focus-browser/browser#259]
The dialog box on dark themes shows the text white and the icon appears inverted see the screenshot below. This works perfectly fine on light themes though.

![dialog popup example](https://github.com/pulse-browser/browser/assets/750774/8ca7283b-7d67-4a07-88a8-9756d571a232)

**Comment by grhkm21** [comment]
I assume this is the same problem, so I will add it here: When adding a bookmark

<img width="434" alt="Screenshot 2023-07-22 at 00 13 24" src="https://github.com/pulse-browser/browser/assets/83517584/9872ff90-84a6-4439-89d3-42cd221a660a">
