### ISSUE TITLE
Anyone else having issues with some PDF's rendering?

### ISSUE THREAD

**Issue by Ivanturas** [focus-browser/browser#261]
No problems when directly opening PDF's so far, but embedded ones look quite garbled up.
![Screenshot 2023-07-06 145251](https://github.com/pulse-browser/browser/assets/66984149/69f25c0e-b5c4-4dcc-8b53-af91ed3aaf9f)

I thought maybe installing Adobe's Acrobat plugin, while hurting performance, would help, but no success so far. I'm pretty sure this has to be something extremely simple to solve. Works fine on Firefox/FF Dev.

**Comment by trickypr** [comment]
Can you provide an example website where this is happening?

Sidenote, that appears to be a custom version of PDFJS, not the one built into Pulse/Gecko.

**Comment by unbound-dynamics** [comment]
I tried on lots of documents from docplayer.net... however, they now display properly. Haven't changed a single setting, so no clue as to what may have happened.

**Comment by trickypr** [comment]
I updated gecko to `115.0.1` a few days ago. It was probably a bug with earlier versions of gecko.
