### ISSUE TITLE
theme resets

### ISSUE THREAD

**Issue by bloodyeyesblackblood** [focus-browser/browser#280]
when i close pulse and open firefox, than open pulse again, the applied theme in this case the pulse one seems to be gone (it's set to automatic)

seems pulse also applies the themes i apply on firefox? but not the other way around?

is this normal? if yes, how can i avoid it?

EDIT: ok could be my bad i think (brainfart), maybe sync? would explain it i don't think the pulse theme is on the mozilla store?

**Comment by trickypr** [comment]
Sync would probably cause that. Because the theme pulse theme uses experimental / internal features (i.e. the `theme_experiment` key) we can't put it on the addon store.

**Comment by bloodyeyesblackblood** [comment]
well idk what it is now, still happens with sync turned off, sad.
