### ISSUE TITLE
Vertical tabs disappear on Windows 11 after full screen content

### ISSUE THREAD

**Issue by EmirYLMZ128** [focus-browser/browser#284]
Windows 11 Pro
version: 22H2
Installed on 17.08.23
OS build 22621.2283
Experience Windows Feature Experience Pack 1000.22662.1000.0

When I exited full screen mode from a yt video, I noticed that there were no vertical tabs.
![Ekran görüntüsü 2023-09-22 100004](https://github.com/pulse-browser/browser/assets/90498438/4a6dec7f-4689-44e4-99d2-a5027fd078bb)

I can dragging to max width value, but the whole thing never appears.
![Ekran görüntüsü 2023-09-22 100017](https://github.com/pulse-browser/browser/assets/90498438/7bab1355-1796-4785-bf0d-685795ea9475)

If I don't move my mouse, only the tabs stay open, but as soon as I move my mouse, they disappear.
![Adsız](https://github.com/pulse-browser/browser/assets/90498438/ca8099de-6383-435d-b76b-42f9c95c1e0f)

**Comment by trickypr** [comment]
Sorry, this was caused by [this commit](https://github.com/pulse-browser/browser/commit/d9581f29d05d4dd064adf670608d5f2fa8b37e88). I really shouldn't be allowed to publish changes after 11pm :/
