### ISSUE TITLE
Sidebar bookmarks Toolbar not open

### ISSUE THREAD

**Issue by EmirYLMZ128** [focus-browser/browser#285]
Windows 11 Pro
version: 22H2
Installed on 17.08.23
OS build 22621.2283
Experience Windows Feature Experience Pack 1000.22662.1000.0

It stays like this when I open the bookmark menu from the sidebar, but it gets fixed after closing and reopening it.
![ss](https://github.com/pulse-browser/browser/assets/90498438/d8b65643-1104-4b03-8142-1ea86d51ca83)

Then the same problem occurs in its subfolders.
![sss](https://github.com/pulse-browser/browser/assets/90498438/2b4d06f5-ba0b-4144-87fc-02a3e2654804)
![Ekran görüntüsü 2023-09-25 105247](https://github.com/pulse-browser/browser/assets/90498438/acb22428-7f88-47b6-a78a-c41b064f3500)

And when I change the location of a bookmark link, I have to reopen it.

**Comment by trickypr** [comment]
This looks like a state persistence issue. Try disabling "Keep sidebar tabs active even when closed" in `about:preferences` and let me know if that fixes it.

**Comment by EmirYLMZ128** [comment]
It worked, thank you.
