### ISSUE TITLE
Youtube Anti-Adblock Message

### ISSUE THREAD

**Issue by eNkiiz** [focus-browser/browser#288]
Just got a youtube anti Ad-Block message, since ublock is integrated i wonder what steps we can take to circumvent this or if the devs themselves will need to update.

**Comment by trickypr** [comment]
We should be shipping the latest version of uBlock. You should consider [refreshing your filter lists](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists). To track upstreams work on this, see [this issue](https://github.com/uBlockOrigin/uAssets/issues/19976).

I encourage you to buy premium if you care about the creators you watch.
